# Generated by Django 5.1.7 on 2025-03-27 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('pk_tag', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('pk_task', models.CharField(primary_key=True, serialize=False)),
                ('tg_id', models.IntegerField(verbose_name='ID пользователя в телеграмме')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок задачи')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('description', models.TextField(max_length=350, verbose_name='Описание задачи')),
                ('date_end', models.DateTimeField(verbose_name='Дата исполнения')),
                ('tags', models.ManyToManyField(related_name='tags', to='tasks_todo.tag', verbose_name='Теги')),
            ],
        ),
    ]
